# MySQL Docker compose file for development purposes. DO NOT USE IN PRODUCTION!

version: '3'

services:
  lighthouse-db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'lighthouse'
      MYSQL_ROOT_PASSWORD: 'lighthouse'
    ports:
      - '3306:3306'
    expose:
      - '3306' # Expose port to localhost:3306
    volumes:
      - lighthouse-db:/var/lib/mysql
  lighthouse-redis:
    image: redis/redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    expose:
      - '6379'
      - '8001'


volumes:
  lighthouse-db: